apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: side-updater

commonLabels:
  app: side-updater

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
