apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # run nginx with non root user
      securityContext:
        runAsUser: 33
        runAsGroup: 33
      containers:
        # serve /usr/share/nginx/html/index.html
        - name: server
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: distinct-updater-data
      volumes:
        - name: distinct-updater-data
          persistentVolumeClaim:
            claimName: distinct-updater-pvc

